server:
  port: 8001

spring:
  application:
    name: cloud-provider-8001
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      password: root
      username: root

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml